export enum DialogTypeEnum {
  AUTH = "auth",
  REGISTER = "register",
  LOGIN = "login",
  DETAIL_HISTORY = "modal-detail-history",
  DETAIL_WITHDRAW_CARD = "modal-detail-withdraw-card",
  ADD_DISPLAY_NAME = "doi-ten",
  BLOCK_GAME = "chan-game",
  VERIFY_EMAIL = "verify-email",
  VERIFY_PHONE = "verify-phone",
  CANCEL_PROMOTION = "huy-khuyen-mai",
  ADD_BANK = "add-bank",
  FORGOT_PASSWORD = "forgot-password",
  RESET_PASSWORD = "reset-password",
  ACCOUNT_OVERVIEW = "account-overview",
  DEPOSIT_MENU = "deposit-menu",
  WITHDRAW_MENU = "withdraw-menu",
  SCHEDULE_MATCH_DETAIL = "lich-thi-dau",
  SCHEDULE_FILTER = "schedule-filter",
  CHANGE_PASSWORD = "change-password",
}
