export enum MappedTransactionHistoryMethodEnum {
  PHONE_CARD = "Thẻ cào",
  IBANKING = "IBanking",
  MOMO = "Momo",
  SMARTPAY = "Paywin",
  SENPAY = "Senpay",
  CODEPAY = "Codepay",
  BANK_ACCOUNT = "Ngân hàng",
  CRYPTOPAY = "Tiền ảo",
  NICEPAY = "CodePay",
  EWALLET_BANKING = "CodePay2",
  P2P = "P2P",
  SYSTEM = "Trả thưởng",
}

export enum MappedTransactionHistoryTitleEnum {
  DEPOSIT = "Nạp",
  WITHDRAW = "Rút",
  PROMOTION = "Khuyến mãi",
  COMMISSION = "Hoàn trả",
  PROMOTION_CANCEL = "Hủy khuyến mãi",
}

export enum MappedTransactionHistoryActionEnum {
  DEPOSIT = "Nạp qua",
  WITHDRAW = "Rút qua",
  PROMOTION = "Cộng tiền thưởng",
  COMMISSION = "Trả thưởng",
}

export enum MappedTransactionHistoryLabelEnum {
  RATE = "Tỷ giá",
  CANCEL_PROMOTION = "Hủy khuyến mãi",
  WATCH_TRANSACTION = "Xem giao dịch",
  DEPOSIT = "Nạp",
  WITHDRAW = "Rút",
  MONEY = "tiền qua",
  INFO_TABLE = "",
  DEPOSIT_NOW = "Nạp ngay",
  DETAIL_TRANSACTIONS = "Chi tiết giao dịch",
  CONTACT = "Trò chuyện với CSKH",
  COPY = "Copy",
  COPYED = "Đã copy",
  TIME = "Thời gian",
  TRANSACTIONS_CODE = "Mã giao dịch",
  METHOD = "Phương thức",
  BANK = "Ngân hàng",
  SENDER = "Người gửi",
  AMOUNT_MONEY = "Số tiền",
  REMITTANCE_CONTENT = "Nội dung chuyển tiền",
  NOTES = "Ghi chú",
  AMOUNT_REWARD = "Số tiền thưởng",
  BANK_NUMBER = "Số tài khoản",
  UNSUCCESSFUL = "Không thành công",
  CHECKED = "Kiểm tra",
  AMOUNT_CRYPTO = "Lượng tiền ảo",
  AMOUNT_RECEIVE = "Số tiền nhận",
  AMOUNT_RECEIVE_WITHDRAW_CRYPTO = "Số tiền rút",
  RECEIVING_WALLET = "Ví nhận",
  TYPE_CRYPTOPAY = "Loại tiền ảo",
  DEPOSIT_WITHDRAW = "Nạp/Rút",
  HOME_NETWORK = "Nhà mạng",
  ID_CARD = "Mã thẻ",
  SERI_NUMBER = "Số seri",
  AMOUNT_BANK = "Số tiền nạp",
  CARD_FEE = "Phí gạch thẻ",
  ACTUALLY_RECEIVED = "Thực nhận",
  ACCOUNT_HOLDER = "Tới tài khoản",
  PHONE = "Số điện thoại",
  STATUS = "Trạng thái",
  TYPE_CARD = "Loại thẻ",
  AMOUNT = "Số lượng",
  SEE_MORE = "[Xem thẻ]",
  CARD = "Chi tiết thẻ cào",
  HISTORY_TRANSACTIONS = "Lịch sử giao dịch",
  HISTORY_BETS = "Lịch sử cá cược",
  DETAIL_BETS = "Chi tiết cá cược",
}

export enum MappedTransactionHistoryStatusEnum {
  FINISHED = "Thành công",
  CANCEL = "Thất bại",
  PROCESSING = "Đang xử lý",
}

export enum TransactionFieldDetailEnum {
  STATUS = "status",
  CODE = "code",
  AMOUNT = "amount",
  WALLET = "wallet",
  WALLET_RECEIVED = "wallet-received",
  CHECKED = "checked",
  MATCH_CODE = "match-code",
}
